### ISSUE TITLE
How to improve the exclusion limit calculation?

### ISSUE THREAD

**Issue by rojalin24** [SpeysideHEP/spey#28] opened 2024-01-23 10:35 UTC
### Question

Hi Jack,
I am trying to recast the exclusion limit on cross-section calculated in the ATLAS analysis for diphoton resonance search: https://arxiv.org/pdf/2102.13405.pdf
I am unable to match my result with the official ATLAS result. For instance, the ATLAS result is 1.1 fb for mass 400 GeV, and I am getting 1.65 fb. I am using the backend 'default_pdf.uncorrelated_background', and no uncertainty on the background. I'm getting a relaxed limit (2.32 fb) using statistical uncertainty. If I use other uncertainty, my result will deviate more from the ATLAS result. 
Please suggest some way to improve my result or to check what is wrong in my calculation. If you need more details, I will share the code and data that I'm using.
Usually, how much mismatch is acceptable in such a calculation?

Thanks for your reply!

**Comment by jackaraz** [comment] 2024-01-23 11:31
Hi @rojalin24, thanks for your question. if you are recasting, I'm assuming that you already implemented the analysis in one of the recasting software, i.e. MadAnalysis, Rivet, CheckMate, etc, and you get the yields from there. If that's the case, you need to be matching to ATLAS yields from there first. Without that, Spey can not produce the exact results even with the full likelihood.

ATLAS internally has access to the full statistical model, so without that, you won't be able to match their results exactly, and all you can do is input all the information available, including the uncertainties, and report the result that you reproduce. Without the full statistical model, knowing how to improve it is impossible. You can test with other statistical model prescriptions available in spey. If the information is available, implementing a covariance matrix usually improves the result; additionally, in [2307.06996](https://arxiv.org/abs/2307.06996), I see that adding asymmetric uncertainties improves the results significantly. But if these have not been provided by the experimental collaboration, there is nothing more you can do.

FYI: if you are not using uncertainties, I suggest using [`"default_pdf.poisson"`](https://spey.readthedocs.io/en/main/plugins.html#default-pdf-poisson) since [`'default_pdf.uncorrelated_background'`](https://spey.readthedocs.io/en/main/plugins.html#default-pdf-uncorrelated-background) may lead to inconsistent results due to the zeros in constraint terms.

**Comment by rojalin24** [comment] 2024-01-23 12:22
Hi Jack,
Thanks a lot for the prompt and detailed answer!
I'm not using any recasting software but implemented analysis in Pythia to calculate the signal yield. For observed and background yields, I'm using the values given in the ATLAS paper. Using my code, I'm getting almost the same cut efficiency for the BSM signal (57%) as given in the ATLAS paper (59%). Do you think such a calculation could be the reason for the mismatch I'm getting?

No information about the covariance/correlation matrix is given as per my knowledge.

**Comment by jackaraz** [comment] 2024-01-23 12:36
Hi @rojalin24, I believe your difference is reasonable. Of course, this will yield some difference in the result, but I believe that is expected already. Unfortunately, I don't know how to improve your results if there is no other information available. The best thing you can do is to report the likelihood that you used along with the result so that your output is consistent and reproducible. Just to emphasize again tho, if you do not have background uncertainties using [`"default_pdf.poisson"`](https://spey.readthedocs.io/en/main/plugins.html#default-pdf-poisson) would make more sense since with [`'default_pdf.uncorrelated_background'`](https://spey.readthedocs.io/en/main/plugins.html#default-pdf-uncorrelated-background) you still have the constraint terms in the likelihood even if your uncertainty is zero, they will dilute the result.

**Comment by rojalin24** [comment] 2024-01-23 12:51
Hi Jack,
Thanks again!
I will check with the using "default_pdf.poisson".

**Comment by jackaraz** [comment] 2024-01-31 14:29
Hi @rojalin24, I believe this is resolved(?) So, closing this issue, please feel free to reopen it if you need further help.

**Closed by jackaraz** 2024-01-31 14:29 UTC
Labels: question
